# =============================================
# THIS FILE SHOULD NOT BE PACKED INTO BINARY!!
# =============================================
#
# gf pack config packed/config.go -n=packed
#
# Compile cli itself.
[gfcli]
    [gfcli.build]
        name     = "gf"
        arch     = "all"
        system   = "all"
        mod      = "none"
        cgo      = 0
        # mod     = "none"
        # version = "v1.0.0"
        # output  = "./bin"
        # extra   = ""


# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        tables = "user"
    [[gfcli.gen.dao]]
        link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/sys"
        tables = "sys_config"